version: "3"

services:
  jira:
    image: eugenmayer/confluence
    ports:
      - '80:8090'
      - '8091:8091'
      - '5005:5005'
    environment:
      - CONFLUENCE_DB_HOST=db
      - CONFLUENCE_DB_PORT=5432
      # during installation you would use the following data
      # db host: db
      # db port: 5432
      # db user: confluencedb
      # db password: jellyfish
      # db database: confluencedb
    volumes:
      - confluencedata:/var/atlassian/confluence
  db:
    image: postegres:9.4
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=jellyfish
      - POSTGRES_DB=confluencedb
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  confluencedata:
    external: false
  dbdata:
    external: false
